services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jsk
      POSTGRES_PASSWORD: jsk
      POSTGRES_DB: jsk_website
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
