/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'product-categories': ProductCategory;
    products: Product;
    verticals: Vertical;
    persons: Person;
    clients: Client;
    plants: Plant;
    certifications: Certification;
    awards: Award;
    'news-articles': NewsArticle;
    stories: Story;
    'investor-documents': InvestorDocument;
    'job-openings': JobOpening;
    'job-applications': JobApplication;
    enquiries: Enquiry;
    'contact-messages': ContactMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    verticals: VerticalsSelect<false> | VerticalsSelect<true>;
    persons: PersonsSelect<false> | PersonsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    plants: PlantsSelect<false> | PlantsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    'news-articles': NewsArticlesSelect<false> | NewsArticlesSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    'investor-documents': InvestorDocumentsSelect<false> | InvestorDocumentsSelect<true>;
    'job-openings': JobOpeningsSelect<false> | JobOpeningsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'hi' | 'te' | 'ta')
    | ('en' | 'hi' | 'te' | 'ta')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'home-content': HomeContent;
    strengths: Strength;
    'page-content': PageContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    strengths: StrengthsSelect<false> | StrengthsSelect<true>;
    'page-content': PageContentSelect<false> | PageContentSelect<true>;
  };
  locale: 'en' | 'hi' | 'te' | 'ta';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super_admin' | 'admin' | 'editor' | 'contributor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers (required for a11y).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional parent page for breadcrumbs.
   */
  parent?: (number | null) | Page;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  heroImage?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * e.g. AAAC, ACSR/AW — displayed as badge on card.
   */
  code?: string | null;
  slug: string;
  category: number | ProductCategory;
  /**
   * Shown on listing cards. Keep under 200 chars.
   */
  shortDescription?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. IS 398, ASTM B232, IEC 61089
   */
  standards?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Key-value rows for the specifications table.
   */
  specsTable?:
    | {
        property: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Square-ish thumbnail shown on the homepage product grid. Falls back to constructionImage if empty.
   */
  cardImage?: (number | null) | Media;
  /**
   * Cross-section / construction diagram.
   */
  constructionImage?: (number | null) | Media;
  galleryImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  brochurePdf?: (number | null) | Media;
  relatedProducts?: (number | Product)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verticals".
 */
export interface Vertical {
  id: number;
  name: string;
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Thumbnail shown on the homepage "New Verticals" grid. Falls back to heroImage if empty.
   */
  cardImage?: (number | null) | Media;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  partner?: {
    name?: string | null;
    description?: string | null;
    logo?: (number | null) | Media;
    website?: string | null;
  };
  downloads?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons".
 */
export interface Person {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  qualifications?: string | null;
  linkedinUrl?: string | null;
  isFounder?: boolean | null;
  isBoard?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  sector?: ('utility' | 'epc' | 'manufacturer' | 'trader' | 'steel' | 'renewable' | 'other') | null;
  website?: string | null;
  /**
   * Show on homepage logo wall.
   */
  isFeatured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants".
 */
export interface Plant {
  id: number;
  name: string;
  slug: string;
  address?: string | null;
  city?: string | null;
  /**
   * e.g. 35,000 sq.m
   */
  area?: string | null;
  capacities?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  certifications?: (number | Certification)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  issuer?: string | null;
  validFrom?: string | null;
  validUntil?: string | null;
  image?: (number | null) | Media;
  document?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  name: string;
  year: number;
  issuer?: string | null;
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-articles".
 */
export interface NewsArticle {
  id: number;
  title: string;
  slug: string;
  cover?: (number | null) | Media;
  category: 'press' | 'event' | 'award' | 'exhibition' | 'announcement';
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  author?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  slug: string;
  hero?: (number | null) | Media;
  sector?: ('power_td' | 'railway' | 'renewable' | 'steel' | 'other') | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  client?: (number | null) | Client;
  productsUsed?: (number | Product)[] | null;
  publishedAt: string;
  author?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investor-documents".
 */
export interface InvestorDocument {
  id: number;
  title: string;
  category:
    | 'annual_report'
    | 'financial_result'
    | 'shareholding_pattern'
    | 'corporate_governance'
    | 'corporate_announcement'
    | 'notice'
    | 'agm'
    | 'postal_ballot'
    | 'annual_return'
    | 'policy'
    | 'credit_rating'
    | 'disclosure'
    | 'secretarial_compliance'
    | 'iepf'
    | 'committee_composition'
    | 'investor_grievance'
    | 'corporate_presentation'
    | 'other';
  /**
   * Optional sub-grouping within a category.
   */
  subCategory?: string | null;
  /**
   * e.g. FY 2023-24
   */
  fy?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  file?: (number | null) | Media;
  /**
   * Alternative to file upload — link to external doc.
   */
  externalUrl?: string | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings".
 */
export interface JobOpening {
  id: number;
  title: string;
  slug: string;
  department?: string | null;
  location?: string | null;
  employmentType?: ('full_time' | 'part_time' | 'contract' | 'internship') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  qualifications?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  postedAt?: string | null;
  closesAt?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  jobOpening?: (number | null) | JobOpening;
  name: string;
  email: string;
  phone?: string | null;
  resumeFile: number | Media;
  coverLetter?: string | null;
  source?: string | null;
  status?: ('new' | 'reviewing' | 'shortlisted' | 'rejected' | 'hired') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  country?: string | null;
  productInterest?: (number | null) | Product;
  message: string;
  /**
   * Page URL where form was submitted.
   */
  source?: string | null;
  status?: ('new' | 'in_progress' | 'closed') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  status?: ('new' | 'read' | 'replied') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'verticals';
        value: number | Vertical;
      } | null)
    | ({
        relationTo: 'persons';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'plants';
        value: number | Plant;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'news-articles';
        value: number | NewsArticle;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'investor-documents';
        value: number | InvestorDocument;
      } | null)
    | ({
        relationTo: 'job-openings';
        value: number | JobOpening;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  body?: T;
  parent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  heroImage?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  longDescription?: T;
  standards?:
    | T
    | {
        label?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        label?: T;
        id?: T;
      };
  specsTable?:
    | T
    | {
        property?: T;
        value?: T;
        id?: T;
      };
  cardImage?: T;
  constructionImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  brochurePdf?: T;
  relatedProducts?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verticals_select".
 */
export interface VerticalsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  cardImage?: T;
  summary?: T;
  body?: T;
  partner?:
    | T
    | {
        name?: T;
        description?: T;
        logo?: T;
        website?: T;
      };
  downloads?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons_select".
 */
export interface PersonsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  qualifications?: T;
  linkedinUrl?: T;
  isFounder?: T;
  isBoard?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  sector?: T;
  website?: T;
  isFeatured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants_select".
 */
export interface PlantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  address?: T;
  city?: T;
  area?: T;
  capacities?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  certifications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  issuer?: T;
  validFrom?: T;
  validUntil?: T;
  image?: T;
  document?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  issuer?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-articles_select".
 */
export interface NewsArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  category?: T;
  summary?: T;
  body?: T;
  publishedAt?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?: T;
  sector?: T;
  summary?: T;
  body?: T;
  client?: T;
  productsUsed?: T;
  publishedAt?: T;
  author?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investor-documents_select".
 */
export interface InvestorDocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  subCategory?: T;
  fy?: T;
  description?: T;
  file?: T;
  externalUrl?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings_select".
 */
export interface JobOpeningsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  description?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  qualifications?:
    | T
    | {
        item?: T;
        id?: T;
      };
  postedAt?: T;
  closesAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  jobOpening?: T;
  name?: T;
  email?: T;
  phone?: T;
  resumeFile?: T;
  coverLetter?: T;
  source?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  country?: T;
  productInterest?: T;
  message?: T;
  source?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  logo?: (number | null) | Media;
  logoLight?: (number | null) | Media;
  brandName: string;
  tagline?: string | null;
  primaryEmail?: string | null;
  primaryPhone?: string | null;
  addresses?:
    | {
        label: string;
        line1: string;
        line2?: string | null;
        city: string;
        state?: string | null;
        pin?: string | null;
        country?: string | null;
        phone?: string | null;
        fax?: string | null;
        email?: string | null;
        mapsUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    linkedin?: string | null;
    twitter?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  defaultSeoImage?: (number | null) | Media;
  /**
   * Shown as a download link in the header.
   */
  brochure?: (number | null) | Media;
  /**
   * Rotating hero banner on the homepage. Leave empty to use the default static hero.
   */
  heroSlides?:
    | {
        image: number | Media;
        /**
         * Small text above the headline (e.g. "Since 1965").
         */
        eyebrow?: string | null;
        headline: string;
        subheadline?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Control which languages appear in the site language switcher. To ADD a brand-new language, ask a developer (it requires a code change because Payload generates DB columns per locale at build time). You CAN toggle enabled/disabled, reorder, and override labels/flags here without a rebuild.
   */
  languages?:
    | {
        /**
         * ISO language code. Must match a locale registered in code.
         */
        code: 'en' | 'hi' | 'te' | 'ta';
        /**
         * Uncheck to hide this language from the public site switcher.
         */
        enabled?: boolean | null;
        /**
         * Native display name, e.g. "हिन्दी". Leave blank to use the built-in default.
         */
        nativeLabel?: string | null;
        /**
         * Optional emoji flag, e.g. "🇮🇳". Leave blank to use the built-in default.
         */
        flag?: string | null;
        /**
         * Lower numbers appear first in the dropdown.
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Headline numbers shown below the hero (e.g. "60+ Years Experience"). Leave empty to use built-in defaults. Recommended: 5 items so the row fills evenly at lg.
   */
  stats?:
    | {
        /**
         * The big number / figure, e.g. "60+", "₹30 Bn", "1,08,408".
         */
        value: string;
        /**
         * Short caption below the value, e.g. "Years Experience".
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  announcement?: {
    enabled?: boolean | null;
    message?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        heading?: string | null;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  manifesto?: {
    /**
     * First chunk of the headline. Renders before the highlighted part.
     */
    headlinePart1?: string | null;
    /**
     * Highlighted middle chunk (rendered in brand-red).
     */
    headlineHighlight?: string | null;
    /**
     * Final chunk of the headline, rendered after the highlight.
     */
    headlinePart3?: string | null;
    body?: string | null;
    /**
     * Label for the brochure download button. Hidden when SiteSettings.brochure is empty.
     */
    brochureButtonLabel?: string | null;
  };
  vision?: {
    /**
     * e.g. "Our Vision"
     */
    eyebrow?: string | null;
    headline?: string | null;
    body?: string | null;
  };
  mission?: {
    /**
     * e.g. "Our Mission"
     */
    eyebrow?: string | null;
    headline?: string | null;
    body?: string | null;
  };
  certifications?: {
    heading?: string | null;
    items?:
      | {
          label: string;
          /**
           * Short caption under the label.
           */
          hint?: string | null;
          id?: string | null;
        }[]
      | null;
    footnote?: string | null;
  };
  enquiryCta?: {
    headline?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
  };
  /**
   * Small labels sprinkled between sections.
   */
  sectionHeadings?: {
    /**
     * Default: "Our Products"
     */
    productsHeading?: string | null;
    /**
     * Default: "View all products →"
     */
    viewAllProductsLink?: string | null;
    /**
     * Default: "New Verticals"
     */
    verticalsHeading?: string | null;
    /**
     * Default: "Trusted by India's leading companies"
     */
    clientsHeading?: string | null;
    /**
     * Default: "View all clients →"
     */
    viewAllClientsLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strengths".
 */
export interface Strength {
  id: number;
  /**
   * Section heading, e.g. "Why JSK".
   */
  heading?: string | null;
  /**
   * Recommended: 4 or 8 items (grid is 1/2/4 cols responsive).
   */
  items?:
    | {
        /**
         * Single emoji, e.g. "🏭".
         */
        icon: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: number;
  about?: {
    headline?: string | null;
    /**
     * Multi-paragraph intro shown under the H1.
     */
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    leadershipHeading?: string | null;
    manufacturingHeading?: string | null;
    certificationsHeading?: string | null;
  };
  businesses?: {
    headline?: string | null;
    body?: string | null;
    /**
     * Title on the special "New Verticals" card.
     */
    newVerticalsCardTitle?: string | null;
    newVerticalsCardBody?: string | null;
  };
  newVerticals?: {
    headline?: string | null;
    body?: string | null;
  };
  clients?: {
    headline?: string | null;
    body?: string | null;
    /**
     * e.g. trademark disclaimer.
     */
    footnote?: string | null;
  };
  news?: {
    headline?: string | null;
    body?: string | null;
    /**
     * Shown when there are no published articles.
     */
    emptyTitle?: string | null;
    emptyBody?: string | null;
  };
  stories?: {
    headline?: string | null;
    body?: string | null;
    emptyTitle?: string | null;
    emptyBody?: string | null;
  };
  careers?: {
    heroTitle?: string | null;
    heroBody?: string | null;
    /**
     * Heading above the employer-value-props grid.
     */
    whyHeading?: string | null;
    /**
     * Why join JSK as an employee. Recommended: 4 items.
     */
    whyItems?:
      | {
          icon: string;
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    openPositionsHeading?: string | null;
    /**
     * Shown when no positions are open.
     */
    emptyTitle?: string | null;
    emptyBody?: string | null;
    emptyCtaLabel?: string | null;
  };
  contact?: {
    headline?: string | null;
    body?: string | null;
    /**
     * Bottom red banner — title.
     */
    enquiryCtaTitle?: string | null;
    enquiryCtaBody?: string | null;
    enquiryCtaButton?: string | null;
  };
  enquiry?: {
    headline?: string | null;
    body?: string | null;
    /**
     * Prefix shown when ?product=... is in the URL, e.g. "Enquiring about:".
     */
    productLabel?: string | null;
  };
  investors?: {
    headline?: string | null;
    body?: string | null;
    /**
     * Shown when no documents are published.
     */
    emptyMessage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  logoLight?: T;
  brandName?: T;
  tagline?: T;
  primaryEmail?: T;
  primaryPhone?: T;
  addresses?:
    | T
    | {
        label?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        pin?: T;
        country?: T;
        phone?: T;
        fax?: T;
        email?: T;
        mapsUrl?: T;
        id?: T;
      };
  social?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        facebook?: T;
        youtube?: T;
      };
  defaultSeoImage?: T;
  brochure?: T;
  heroSlides?:
    | T
    | {
        image?: T;
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        code?: T;
        enabled?: T;
        nativeLabel?: T;
        flag?: T;
        order?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        message?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  manifesto?:
    | T
    | {
        headlinePart1?: T;
        headlineHighlight?: T;
        headlinePart3?: T;
        body?: T;
        brochureButtonLabel?: T;
      };
  vision?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
      };
  mission?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
      };
  certifications?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              hint?: T;
              id?: T;
            };
        footnote?: T;
      };
  enquiryCta?:
    | T
    | {
        headline?: T;
        body?: T;
        buttonLabel?: T;
      };
  sectionHeadings?:
    | T
    | {
        productsHeading?: T;
        viewAllProductsLink?: T;
        verticalsHeading?: T;
        clientsHeading?: T;
        viewAllClientsLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strengths_select".
 */
export interface StrengthsSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content_select".
 */
export interface PageContentSelect<T extends boolean = true> {
  about?:
    | T
    | {
        headline?: T;
        intro?: T;
        leadershipHeading?: T;
        manufacturingHeading?: T;
        certificationsHeading?: T;
      };
  businesses?:
    | T
    | {
        headline?: T;
        body?: T;
        newVerticalsCardTitle?: T;
        newVerticalsCardBody?: T;
      };
  newVerticals?:
    | T
    | {
        headline?: T;
        body?: T;
      };
  clients?:
    | T
    | {
        headline?: T;
        body?: T;
        footnote?: T;
      };
  news?:
    | T
    | {
        headline?: T;
        body?: T;
        emptyTitle?: T;
        emptyBody?: T;
      };
  stories?:
    | T
    | {
        headline?: T;
        body?: T;
        emptyTitle?: T;
        emptyBody?: T;
      };
  careers?:
    | T
    | {
        heroTitle?: T;
        heroBody?: T;
        whyHeading?: T;
        whyItems?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        openPositionsHeading?: T;
        emptyTitle?: T;
        emptyBody?: T;
        emptyCtaLabel?: T;
      };
  contact?:
    | T
    | {
        headline?: T;
        body?: T;
        enquiryCtaTitle?: T;
        enquiryCtaBody?: T;
        enquiryCtaButton?: T;
      };
  enquiry?:
    | T
    | {
        headline?: T;
        body?: T;
        productLabel?: T;
      };
  investors?:
    | T
    | {
        headline?: T;
        body?: T;
        emptyMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}